In [ ]:
#Name- Sara Potey
#PRN- 25070123102
#Experiment-10
#Aim- Study of Pandas library

In [ ]:
#Introduction to Pandas
# Pandas: Panel Data
'''Used for:
Structured data
EDA
Data cleaning'''

In [2]:
import pandas as pd
s= pd.Series([10,20,30,40])
print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [19]:
#Create DataFrame
data={
    "Name":["A","B","C"],
    "Marks":[85,90,78]
}
df=pd.DataFrame(data)
print(df)

#Find the structure of the DataFrame
print(df.shape)

print(df.ndim)

print(df.size)

# Display column names
print(df.columns)

#Check data types of each column
print (df.dtypes)

#Access individual column
df["Name"]

  Name  Marks
0    A     85
1    B     90
2    C     78
(3, 2)
2
6
Index(['Name', 'Marks'], dtype='object')
Name     object
Marks     int64
dtype: object

0    A
1    B
2    C
Name: Name, dtype: object

df.head()

df.tail()

In [18]:
#Access specific row
df.loc[0]

Name      A
Marks    85
Name: 0, dtype: object

In [17]:
df.iloc[1,1]

np.int64(90)

In [25]:
#Add a new column
'''If marks 80-90-first class
If marks>=90-Distinction
If marks>80-Second class'''
df["Grade"]=["First Class","Distinction","Second Class"]
display(df)

  Name  Marks         Grade
0    A     85   First Class
1    B     90   Distinction
2    C     78  Second Class

In [26]:
#Update data in data frame
#Change marks of student A to 88.
df.iloc[0,1]=81
df

  Name  Marks         Grade
0    A     81   First Class
1    B     90   Distinction
2    C     78  Second Class

In [27]:
df.loc[0,"Marks"]=81
df

  Name  Marks         Grade
0    A     81   First Class
1    B     90   Distinction
2    C     78  Second Class

In [28]:
#Delete a column
df.drop("Grade", axis=1, inplace=True)
df

  Name  Marks
0    A     81
1    B     90
2    C     78

In [30]:
new_df=df.drop("Name",axis=1)
display("the new column is:",new_df)
print()

'the new column is:'

   Marks
0     81
1     90
2     78

In [31]:
#To perform basic statistical analysis
mean1=df["Marks"].mean()
mean1

np.float64(83.0)

In [32]:
min1=df["Marks"].min()
min1

78

In [33]:
max1=df["Marks"].max()
max1

90

In [34]:
#Apply condition (filtering)
#Display students scoring more than 80.
df[df["Marks"]>80]

  Name  Marks
0    A     81
1    B     90